// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Galabau Butzbach",
    "city": "Sandhausen",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "Garten, Pflaster und Terrasse in Sandhausen.",
  "heroSubline": "Von der Einfahrt bis zur fertigen Gartenanlage: Erdarbeiten, Pflaster, Terrasse, Zaun, Bewässerung und Pflege. Im Einsatz in Sandhausen, Heidelberg, Leimen, Walldorf und rund 40 km Umkreis.",
  "services": [
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom leeren Grundstück oder zugewachsenen Garten zur fertigen Anlage: Erdarbeiten, Wege, Treppen, Beete, Rasen.",
      "intro": "Eine Neuanlage ist selten nur Bepflanzung. Meistens hängen Erdarbeiten, Hangbefestigung, Entwässerung, Treppen, Wege und Terrasse mit daran. Diese Gewerke machen wir selbst und planen sie in einem Zug, damit die Höhen zusammenpassen und der Garten am Ende nicht aus Einzelteilen besteht. Wir arbeiten im Privatgarten ebenso wie an größeren Anlagen und öffentlichen Flächen.",
      "bullets": [
        "Erdarbeiten, Geländemodellierung, Hangbefestigung und Entsorgung des Aushubs",
        "Rasenneuanlage, Pflanzungen, Hochbeete sowie Kies- und Mulchgärten",
        "Treppen, Wege und Terrasse mit vorher festgelegten Höhen und Gefälle",
        "Wasseranlagen, Gartenbeleuchtung und Gerätehaus auf Wunsch mitgeplant",
        "Aufmaß vor Ort, die Budgetspannen hier sind reine Orientierung"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zugang, Boden und Gefälle und klären, was baulich sinnvoll ist."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten und Terrasse meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Sandhausen | Galabau Butzbach",
        "description": "Gartenneugestaltung in Sandhausen, Heidelberg und Umgebung: Erdarbeiten, Hangbefestigung, Treppen, Wege, Rasen und Bepflanzung. Aufmaß vor Ort, klare Positionen."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Stellplatz, Hof und Wege mit tragfähigem Unterbau und geplanter Entwässerung.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, legen das Gefälle vorher fest und klären die Entwässerung, bevor der erste Stein liegt. Einfahrt, Stellplatz, Hof und Gartenweg rechnen wir nach Quadratmetern.",
      "bullets": [
        "Einfahrten, Stellplätze, Zufahrten, Höfe und Gartenwege",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Außentreppen, Randeinfassungen und Anschlüsse an Bestandsflächen",
        "Entwässerung, Rinnen und Versickerung von Anfang an eingeplant",
        "Mülltonnenboxen und Stellplatzabtrennungen passend zur Fläche"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Sandhausen | Galabau Butzbach",
        "description": "Pflasterarbeiten für Einfahrt, Stellplatz, Hof und Wege: tragfähiger Unterbau nach Belastung, geplante Entwässerung, Außentreppen und Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen in Beton und Feinsteinzeug oder in Holz und WPC, inklusive Unterbau und Beleuchtung.",
      "intro": "Wir bauen Terrassen in zwei Richtungen: Beton- und Feinsteinplatten im Splittbett oder auf Stelzlagern, und Holz beziehungsweise WPC auf belüfteter Unterkonstruktion. Wie die Fläche nach fünf Jahren aussieht, entscheiden Anschlusshöhe, Unterbau und Entwässerung, nicht das Muster im Prospekt.",
      "bullets": [
        "Beton- und Feinsteinplatten im Splittbett oder auf Stelzlagern",
        "Holz- und WPC-Dielen auf belüfteter Unterkonstruktion",
        "Anschlusshöhen an Türschwellen und Gefälle vorher festgelegt",
        "Sichtschutz, Ruhefläche und Übergang zum Rasen mitgeplant",
        "Gartenbeleuchtung und Leerrohre vor dem Belag verlegt"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Holz oder Feinsteinzeug?",
          "a": "Holz ist warm und lebendig, braucht aber regelmäßige Pflege und arbeitet mit dem Wetter. Feinsteinzeug und Beton sind pflegeleicht und farbstabil, dafür fühlen sie sich kühler an. Wir zeigen Ihnen beides an gebauten Flächen, bevor Sie sich festlegen."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Sandhausen | Galabau Butzbach",
        "description": "Terrassenbau in Beton und Feinsteinzeug oder in Holz und WPC: Splittbett, Stelzlager oder Unterkonstruktion, mit Gefälle, Sichtschutz und Beleuchtung."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmalige Pflege oder fester Pflegevertrag: Rasen, Hecken, Beete, Baumfällung und Winterdienst.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart sich den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn ein Garten über Jahre zugewachsen ist, und die laufende Pflege über die Saison, auf Wunsch inklusive Winterdienst.",
      "bullets": [
        "Einmalpflege für zugewachsene Gärten inklusive Abtransport",
        "Laufende Pflege mit festen Terminen über die Saison",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat und Düngung",
        "Hecken- und Formschnitt, Rückschnitt von Sträuchern, Baumfällungen",
        "Laubräumung und Winterdienst auf Wunsch mit im Vertrag"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        },
        {
          "q": "Darf ein Baum einfach gefällt werden?",
          "a": "Nicht immer. Viele Gemeinden haben eine Baumschutzsatzung, und zusätzlich gilt die gesetzliche Schonzeit. Wir sehen uns den Baum an und sagen Ihnen, ob eine Genehmigung nötig ist, bevor wir anrücken."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Sandhausen | Galabau Butzbach",
        "description": "Gartenpflege als Einmalpflege oder Pflegevertrag: Rasen, Heckenschnitt, Beete, Baumfällung und Winterdienst mit festen Terminen."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Zäune, Sichtschutzwände und Gabionen, kalkuliert nach laufenden Metern.",
      "intro": "Zaun und Sichtschutz rechnen wir nach laufenden Metern. Entscheidend sind Höhe, Fundament und Grenzverlauf. Gabionen brauchen zusätzlich einen tragfähigen Untergrund, weil die Steinfüllung dauerhaft Gewicht auf die Fläche bringt. Wo eine Genehmigung oder eine Abstimmung mit dem Nachbarn nötig ist, sagen wir das vorher.",
      "bullets": [
        "Doppelstabmatten, Holz, WPC und Aluminium",
        "Gabionen mit tragfähigem Unterbau und passender Steinfüllung",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Tore und Gartentüren mit passender Beschlagtechnik",
        "Hinweise zu Grenzverlauf, Höhe und örtlicher Satzung vor der Montage"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun & Sichtschutz in Sandhausen | Galabau Butzbach",
        "description": "Zaun und Sichtschutz nach laufenden Metern: Doppelstabmatten, Holz, Gabionen, mit Fundament und Hinweisen zur Genehmigung."
      }
    },
    {
      "key": "bewaesserung",
      "slug": "bewaesserung",
      "label": "Bewässerung",
      "navLabel": "Bewässerung",
      "cta": "Bewässerung prüfen",
      "unit": "qm",
      "teaser": "Automatische Bewässerung für Rasen und Beete, dazu Mähroboter-Flächen samt Begrenzungskabel.",
      "intro": "Eine automatische Bewässerung spart Wasser, weil sie früh morgens und nach Bedarf läuft. Entscheidend ist die Auslegung: Druck, Durchfluss und Kreise müssen zusammenpassen, sonst bleibt ein Teil der Fläche trocken. Begrenzungskabel für Mähroboter verlegen wir im selben Arbeitsgang.",
      "bullets": [
        "Auslegung nach Druck, Durchfluss und Flächenzuschnitt",
        "Getrennte Kreise für Rasen, Beete und Tropfbewässerung",
        "Steuerung mit Regensensor, auf Wunsch mit App-Anbindung",
        "Mähroboter: Begrenzungskabel verlegen und Fläche einrichten",
        "Nachrüstung im Bestand, Inbetriebnahme im Frühjahr und Einwintern"
      ],
      "ablauf": [
        {
          "title": "Fläche & Wasser",
          "text": "Wir brauchen Flächengröße sowie Druck und Durchfluss am Hausanschluss."
        },
        {
          "title": "Auslegung",
          "text": "Kreise, Regner und Tropflinien werden auf die Fläche gerechnet."
        },
        {
          "title": "Angebot",
          "text": "Material, Verlegung und Steuerung transparent aufgeschlüsselt."
        },
        {
          "title": "Einbau",
          "text": "Verlegen, Einregulieren, Programmierung und Einweisung."
        }
      ],
      "faq": [
        {
          "q": "Muss der Rasen dafür raus?",
          "a": "Nein. Wir verlegen mit einem Verlegepflug, die Schnitte wachsen in der Regel innerhalb weniger Wochen zu."
        },
        {
          "q": "Was kostet die Wartung?",
          "a": "Inbetriebnahme und Einwintern sind planbare Pauschalen, die wir mit dem Angebot ausweisen."
        }
      ],
      "image": "/assets/leistungen/bewaesserung-rasen-und-beete.webp",
      "estimate": {
        "minPerUnit": 12,
        "maxPerUnit": 35,
        "baseMin": 1800
      },
      "seo": {
        "title": "Bewässerung in Sandhausen | Galabau Butzbach",
        "description": "Automatische Bewässerung für Rasen und Beete: Auslegung nach Druck und Durchfluss, Steuerung mit Regensensor, Mähroboter-Kabel, Nachrüstung und Wartung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Sandhausen",
    "radiusKm": 40,
    "note": "Im Kern arbeiten wir in den Postleitzahlgebieten 68 und 69, von Sandhausen über Heidelberg und Leimen bis Schwetzingen und Mannheim. Richtung Speyer, Bruchsal, Sinsheim und Bergstraße fahren wir ab einer gewissen Projektgröße, das klären wir vorab am Telefon. Weiter entfernte Anfragen sagen wir lieber ab, als einen Termin nicht halten zu können.",
    "plzPrefixes": [
      "68",
      "69"
    ],
    "borderPlzPrefixes": [
      "64",
      "67",
      "74",
      "76"
    ],
    "places": [
      "Sandhausen",
      "Heidelberg",
      "Leimen",
      "Nußloch",
      "Walldorf",
      "Wiesloch",
      "Oftersheim",
      "Plankstadt",
      "Eppelheim",
      "Schwetzingen",
      "Hockenheim",
      "Mannheim"
    ],
    "center": {
      "lat": 49.3465052,
      "lng": 8.6519915
    }
  },
  "contact": {
    "phone": "0176 22504404",
    "phoneLink": "tel:+4917622504404",
    "whatsapp": "0176 22504404",
    "whatsappLink": "https://wa.me/4917622504404",
    "whatsappPrefill": "Hallo Galabau Butzbach, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Helfer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir suchen Verstärkung für unsere Baustellen im Raum Sandhausen, Heidelberg und Schwetzingen: Pflaster und Terrasse, Erdarbeiten, Zaunbau, Pflanzungen und Pflege. Erzählen Sie uns kurz, was Sie können und was Sie schon gemacht haben. Den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Pflasterer/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in"
    ],
    "benefits": [
      "Baustellen im Umkreis von rund 40 km, abends sind Sie zu Hause",
      "Kleiner Betrieb, kurze Wege: Sie sprechen direkt mit dem Chef",
      "Pflege und Winterdienst sichern Arbeit auch in der kalten Jahreszeit",
      "Arbeitskleidung, Werkzeug und Maschinen stellt der Betrieb",
      "Maschinen- und Führerscheinkurse sind möglich, wenn sie zum Betrieb passen"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Beratung vor dem Preis",
        "text": "Erst der Ortstermin und das Aufmaß, dann die Zahl. Was baulich nicht sinnvoll ist, sagen wir vorher."
      },
      {
        "label": "Alle Gewerke aus einem Betrieb",
        "text": "Erdarbeiten, Pflaster, Terrasse, Zaun, Bewässerung und Bepflanzung laufen bei uns zusammen. Sie koordinieren keine vier Firmen."
      },
      {
        "label": "Ein Ansprechpartner",
        "text": "Vom Aufmaß bis zur Abnahme bleibt der Kontakt derselbe, auch bei Rückfragen nach der Übergabe."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
